; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Thu Aug 06 2020 17:28:33 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

